name: Lloydwilliams
favicon: null
layout_spectrum: 0.627258385065943
typography_spectrum: 0.5105674837250262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5528202822897583
  lightness: 0.31682625133544207
  saturation: 0.3849144314881414
  rhythmicContrast: 0.8874315319117159
purpose: []
